<select id="timezone">
	<option value=""></option>
	<option value="America/Adak">(GMT -10:00) Adak</option>
	<option value="US/Aleutian">(GMT -10:00) Aleutian</option>
	<option value="America/Atka">(GMT -10:00) Atka</option>
	<option value="US/Alaska">(GMT -09:00) Alaska</option>
	<option value="America/Anchorage">(GMT -09:00) Anchorage</option>
	<option value="America/Juneau">(GMT -09:00) Juneau</option>
	<option value="America/Nome">(GMT -09:00) Nome</option>
	<option value="America/Yakutat">(GMT -09:00) Yakutat</option>
	<option value="Mexico/BajaNorte">(GMT -08:00) BajaNorte</option>
	<option value="America/Dawson">(GMT -08:00) Dawson</option>
	<option value="America/Ensenada">(GMT -08:00) Ensenada</option>
	<option value="America/Los_Angeles">(GMT -08:00) Los Angeles</option>
	<option value="Canada/Pacific">(GMT -08:00) Pacific</option>
	<option value="US/Pacific">(GMT -08:00) Pacific</option>
	<option value="US/Pacific-New">(GMT -08:00) Pacific-New</option>
	<option value="America/Tijuana">(GMT -08:00) Tijuana</option>
	<option value="America/Vancouver">(GMT -08:00) Vancouver</option>
	<option value="America/Whitehorse">(GMT -08:00) Whitehorse</option>
	<option value="Canada/Yukon">(GMT -08:00) Yukon</option>
	<option value="Mexico/BajaSur">(GMT -07:00) BajaSur</option>
	<option value="America/Boise">(GMT -07:00) Boise</option>
	<option value="America/Cambridge_Bay">(GMT -07:00) Cambridge Bay</option>
	<option value="America/Chihuahua">(GMT -07:00) Chihuahua</option>
	<option value="America/Denver">(GMT -07:00) Denver</option>
	<option value="America/Edmonton">(GMT -07:00) Edmonton</option>
	<option value="America/Inuvik">(GMT -07:00) Inuvik</option>
	<option value="America/Mazatlan">(GMT -07:00) Mazatlan</option>
	<option value="Canada/Mountain">(GMT -07:00) Mountain</option>
	<option value="US/Mountain">(GMT -07:00) Mountain</option>
	<option value="America/Shiprock">(GMT -07:00) Shiprock</option>
	<option value="America/Yellowknife">(GMT -07:00) Yellowknife</option>
	<option value="America/Cancun">(GMT -06:00) Cancun</option>
	<option value="Canada/Central">(GMT -06:00) Central</option>
	<option value="US/Central">(GMT -06:00) Central</option>
	<option value="America/Chicago">(GMT -06:00) Chicago</option>
	<option value="Pacific/Easter">(GMT -06:00) Easter</option>
	<option value="Chile/EasterIsland">(GMT -06:00) EasterIsland</option>
	<option value="Mexico/General">(GMT -06:00) General</option>
	<option value="US/Indiana-Starke">(GMT -06:00) Indiana-Starke</option>
	<option value="America/Indiana/Knox">(GMT -06:00) Indiana - Knox</option>
	<option value="America/Indiana/Tell_City">(GMT -06:00) Indiana - Tell City</option>
	<option value="America/Knox_IN">(GMT -06:00) Knox IN</option>
	<option value="America/Menominee">(GMT -06:00) Menominee</option>
	<option value="America/Merida">(GMT -06:00) Merida</option>
	<option value="America/Mexico_City">(GMT -06:00) Mexico City</option>
	<option value="America/Monterrey">(GMT -06:00) Monterrey</option>
	<option value="America/North_Dakota/Center">(GMT -06:00) North Dakota - Center</option>
	<option value="America/North_Dakota/New_Salem">(GMT -06:00) North Dakota - New Salem</option>
	<option value="America/Rainy_River">(GMT -06:00) Rainy River</option>
	<option value="America/Rankin_Inlet">(GMT -06:00) Rankin Inlet</option>
	<option value="America/Winnipeg">(GMT -06:00) Winnipeg</option>
	<option value="America/Detroit">(GMT -05:00) Detroit</option>
	<option value="US/East-Indiana">(GMT -05:00) East-Indiana</option>
	<option value="Canada/Eastern">(GMT -05:00) Eastern</option>
	<option value="US/Eastern">(GMT -05:00) Eastern</option>
	<option value="America/Fort_Wayne">(GMT -05:00) Fort Wayne</option>
	<option value="America/Grand_Turk">(GMT -05:00) Grand Turk</option>
	<option value="America/Havana">(GMT -05:00) Havana</option>
	<option value="America/Indiana/Indianapolis">(GMT -05:00) Indiana - Indianapolis</option>
	<option value="America/Indiana/Marengo">(GMT -05:00) Indiana - Marengo</option>
	<option value="America/Indiana/Petersburg">(GMT -05:00) Indiana - Petersburg</option>
	<option value="America/Indiana/Vevay">(GMT -05:00) Indiana - Vevay</option>
	<option value="America/Indiana/Vincennes">(GMT -05:00) Indiana - Vincennes</option>
	<option value="America/Indiana/Winamac">(GMT -05:00) Indiana - Winamac</option>
	<option value="America/Indianapolis">(GMT -05:00) Indianapolis</option>
	<option value="America/Iqaluit">(GMT -05:00) Iqaluit</option>
	<option value="America/Kentucky/Louisville">(GMT -05:00) Kentucky - Louisville</option>
	<option value="America/Kentucky/Monticello">(GMT -05:00) Kentucky - Monticello</option>
	<option value="America/Louisville">(GMT -05:00) Louisville</option>
	<option value="US/Michigan">(GMT -05:00) Michigan</option>
	<option value="America/Montreal">(GMT -05:00) Montreal</option>
	<option value="America/Nassau">(GMT -05:00) Nassau</option>
	<option value="America/New_York">(GMT -05:00) New York</option>
	<option value="America/Nipigon">(GMT -05:00) Nipigon</option>
	<option value="America/Pangnirtung">(GMT -05:00) Pangnirtung</option>
	<option value="America/Resolute">(GMT -05:00) Resolute</option>
	<option value="America/Thunder_Bay">(GMT -05:00) Thunder Bay</option>
	<option value="America/Toronto">(GMT -05:00) Toronto</option>
	<option value="America/Argentina/San_Luis">(GMT -04:00) Argentina - San Luis</option>
	<option value="America/Asuncion">(GMT -04:00) Asuncion</option>
	<option value="Canada/Atlantic">(GMT -04:00) Atlantic</option>
	<option value="Atlantic/Bermuda">(GMT -04:00) Bermuda</option>
	<option value="America/Campo_Grande">(GMT -04:00) Campo Grande</option>
	<option value="Chile/Continental">(GMT -04:00) Continental</option>
	<option value="America/Cuiaba">(GMT -04:00) Cuiaba</option>
	<option value="America/Glace_Bay">(GMT -04:00) Glace Bay</option>
	<option value="America/Goose_Bay">(GMT -04:00) Goose Bay</option>
	<option value="America/Halifax">(GMT -04:00) Halifax</option>
	<option value="America/Moncton">(GMT -04:00) Moncton</option>
	<option value="Antarctica/Palmer">(GMT -04:00) Palmer</option>
	<option value="America/Santiago">(GMT -04:00) Santiago</option>
	<option value="Atlantic/Stanley">(GMT -04:00) Stanley</option>
	<option value="America/Thule">(GMT -04:00) Thule</option>
	<option value="Canada/Newfoundland">(GMT -03:30) Newfoundland</option>
	<option value="America/St_Johns">(GMT -03:30) St Johns</option>
	<option value="Brazil/East">(GMT -03:00) East</option>
	<option value="America/Godthab">(GMT -03:00) Godthab</option>
	<option value="America/Miquelon">(GMT -03:00) Miquelon</option>
	<option value="America/Montevideo">(GMT -03:00) Montevideo</option>
	<option value="America/Sao_Paulo">(GMT -03:00) Sao Paulo</option>
	<option value="Atlantic/Azores">(GMT -01:00) Azores</option>
	<option value="America/Scoresbysund">(GMT -01:00) Scoresbysund</option>
	<option value="Africa/Abidjan">(GMT) Abidjan</option>
	<option value="Africa/Accra">(GMT) Accra</option>
	<option value="Brazil/Acre">(GMT) Acre</option>
	<option value="Africa/Addis_Ababa">(GMT) Addis Ababa</option>
	<option value="Asia/Aden">(GMT) Aden</option>
	<option value="Africa/Algiers">(GMT) Algiers</option>
	<option value="Asia/Almaty">(GMT) Almaty</option>
	<option value="America/Anguilla">(GMT) Anguilla</option>
	<option value="Indian/Antananarivo">(GMT) Antananarivo</option>
	<option value="America/Antigua">(GMT) Antigua</option>
	<option value="Pacific/Apia">(GMT) Apia</option>
	<option value="Asia/Aqtau">(GMT) Aqtau</option>
	<option value="Asia/Aqtobe">(GMT) Aqtobe</option>
	<option value="America/Araguaina">(GMT) Araguaina</option>
	<option value="America/Argentina/Buenos_Aires">(GMT) Argentina - Buenos Aires</option>
	<option value="America/Argentina/Catamarca">(GMT) Argentina - Catamarca</option>
	<option value="America/Argentina/ComodRivadavia">(GMT) Argentina - ComodRivadavia</option>
	<option value="America/Argentina/Cordoba">(GMT) Argentina - Cordoba</option>
	<option value="America/Argentina/Jujuy">(GMT) Argentina - Jujuy</option>
	<option value="America/Argentina/La_Rioja">(GMT) Argentina - La Rioja</option>
	<option value="America/Argentina/Mendoza">(GMT) Argentina - Mendoza</option>
	<option value="America/Argentina/Rio_Gallegos">(GMT) Argentina - Rio Gallegos</option>
	<option value="America/Argentina/Salta">(GMT) Argentina - Salta</option>
	<option value="America/Argentina/San_Juan">(GMT) Argentina - San Juan</option>
	<option value="America/Argentina/Tucuman">(GMT) Argentina - Tucuman</option>
	<option value="America/Argentina/Ushuaia">(GMT) Argentina - Ushuaia</option>
	<option value="US/Arizona">(GMT) Arizona</option>
	<option value="America/Aruba">(GMT) Aruba</option>
	<option value="Asia/Ashgabat">(GMT) Ashgabat</option>
	<option value="Asia/Ashkhabad">(GMT) Ashkhabad</option>
	<option value="Africa/Asmara">(GMT) Asmara</option>
	<option value="Africa/Asmera">(GMT) Asmera</option>
	<option value="America/Atikokan">(GMT) Atikokan</option>
	<option value="Asia/Baghdad">(GMT) Baghdad</option>
	<option value="America/Bahia">(GMT) Bahia</option>
	<option value="Asia/Bahrain">(GMT) Bahrain</option>
	<option value="Africa/Bamako">(GMT) Bamako</option>
	<option value="Asia/Bangkok">(GMT) Bangkok</option>
	<option value="Africa/Bangui">(GMT) Bangui</option>
	<option value="Africa/Banjul">(GMT) Banjul</option>
	<option value="America/Barbados">(GMT) Barbados</option>
	<option value="America/Belem">(GMT) Belem</option>
	<option value="Europe/Belfast">(GMT) Belfast</option>
	<option value="America/Belize">(GMT) Belize</option>
	<option value="Asia/Bishkek">(GMT) Bishkek</option>
	<option value="Africa/Bissau">(GMT) Bissau</option>
	<option value="America/Blanc-Sablon">(GMT) Blanc-Sablon</option>
	<option value="Africa/Blantyre">(GMT) Blantyre</option>
	<option value="America/Boa_Vista">(GMT) Boa Vista</option>
	<option value="America/Bogota">(GMT) Bogota</option>
	<option value="Africa/Brazzaville">(GMT) Brazzaville</option>
	<option value="Australia/Brisbane">(GMT) Brisbane</option>
	<option value="Asia/Brunei">(GMT) Brunei</option>
	<option value="America/Buenos_Aires">(GMT) Buenos Aires</option>
	<option value="Asia/Calcutta">(GMT) Calcutta</option>
	<option value="Atlantic/Canary">(GMT) Canary</option>
	<option value="Atlantic/Cape_Verde">(GMT) Cape Verde</option>
	<option value="America/Caracas">(GMT) Caracas</option>
	<option value="Africa/Casablanca">(GMT) Casablanca</option>
	<option value="Antarctica/Casey">(GMT) Casey</option>
	<option value="America/Catamarca">(GMT) Catamarca</option>
	<option value="America/Cayenne">(GMT) Cayenne</option>
	<option value="America/Cayman">(GMT) Cayman</option>
	<option value="Indian/Chagos">(GMT) Chagos</option>
	<option value="Asia/Choibalsan">(GMT) Choibalsan</option>
	<option value="Asia/Chongqing">(GMT) Chongqing</option>
	<option value="Asia/Chungking">(GMT) Chungking</option>
	<option value="Asia/Colombo">(GMT) Colombo</option>
	<option value="Indian/Comoro">(GMT) Comoro</option>
	<option value="Africa/Conakry">(GMT) Conakry</option>
	<option value="America/Coral_Harbour">(GMT) Coral Harbour</option>
	<option value="America/Cordoba">(GMT) Cordoba</option>
	<option value="America/Costa_Rica">(GMT) Costa Rica</option>
	<option value="America/Curacao">(GMT) Curacao</option>
	<option value="Asia/Dacca">(GMT) Dacca</option>
	<option value="Africa/Dakar">(GMT) Dakar</option>
	<option value="America/Danmarkshavn">(GMT) Danmarkshavn</option>
	<option value="Africa/Dar_es_Salaam">(GMT) Dar es Salaam</option>
	<option value="Australia/Darwin">(GMT) Darwin</option>
	<option value="Antarctica/Davis">(GMT) Davis</option>
	<option value="America/Dawson_Creek">(GMT) Dawson Creek</option>
	<option value="Brazil/DeNoronha">(GMT) DeNoronha</option>
	<option value="Asia/Dhaka">(GMT) Dhaka</option>
	<option value="Asia/Dili">(GMT) Dili</option>
	<option value="Africa/Djibouti">(GMT) Djibouti</option>
	<option value="America/Dominica">(GMT) Dominica</option>
	<option value="Africa/Douala">(GMT) Douala</option>
	<option value="Asia/Dubai">(GMT) Dubai</option>
	<option value="Europe/Dublin">(GMT) Dublin</option>
	<option value="Antarctica/DumontDUrville">(GMT) DumontDUrville</option>
	<option value="Asia/Dushanbe">(GMT) Dushanbe</option>
	<option value="Canada/East-Saskatchewan">(GMT) East-Saskatchewan</option>
	<option value="Pacific/Efate">(GMT) Efate</option>
	<option value="America/Eirunepe">(GMT) Eirunepe</option>
	<option value="Africa/El_Aaiun">(GMT) El Aaiun</option>
	<option value="America/El_Salvador">(GMT) El Salvador</option>
	<option value="Pacific/Enderbury">(GMT) Enderbury</option>
	<option value="Australia/Eucla">(GMT) Eucla</option>
	<option value="Atlantic/Faeroe">(GMT) Faeroe</option>
	<option value="Atlantic/Faroe">(GMT) Faroe</option>
	<option value="Pacific/Fiji">(GMT) Fiji</option>
	<option value="America/Fortaleza">(GMT) Fortaleza</option>
	<option value="Africa/Freetown">(GMT) Freetown</option>
	<option value="Africa/Gaborone">(GMT) Gaborone</option>
	<option value="Pacific/Galapagos">(GMT) Galapagos</option>
	<option value="Pacific/Gambier">(GMT) Gambier</option>
	<option value="America/Grenada">(GMT) Grenada</option>
	<option value="Pacific/Guadalcanal">(GMT) Guadalcanal</option>
	<option value="America/Guadeloupe">(GMT) Guadeloupe</option>
	<option value="Pacific/Guam">(GMT) Guam</option>
	<option value="America/Guatemala">(GMT) Guatemala</option>
	<option value="America/Guayaquil">(GMT) Guayaquil</option>
	<option value="Europe/Guernsey">(GMT) Guernsey</option>
	<option value="America/Guyana">(GMT) Guyana</option>
	<option value="Africa/Harare">(GMT) Harare</option>
	<option value="Asia/Harbin">(GMT) Harbin</option>
	<option value="US/Hawaii">(GMT) Hawaii</option>
	<option value="America/Hermosillo">(GMT) Hermosillo</option>
	<option value="Asia/Ho_Chi_Minh">(GMT) Ho Chi Minh</option>
	<option value="Asia/Hong_Kong">(GMT) Hong Kong</option>
	<option value="Pacific/Honolulu">(GMT) Honolulu</option>
	<option value="Asia/Hovd">(GMT) Hovd</option>
	<option value="Europe/Isle_of_Man">(GMT) Isle of Man</option>
	<option value="Asia/Jakarta">(GMT) Jakarta</option>
	<option value="America/Jamaica">(GMT) Jamaica</option>
	<option value="Asia/Jayapura">(GMT) Jayapura</option>
	<option value="Europe/Jersey">(GMT) Jersey</option>
	<option value="Africa/Johannesburg">(GMT) Johannesburg</option>
	<option value="America/Jujuy">(GMT) Jujuy</option>
	<option value="Asia/Kabul">(GMT) Kabul</option>
	<option value="Africa/Kampala">(GMT) Kampala</option>
	<option value="Asia/Kashgar">(GMT) Kashgar</option>
	<option value="Asia/Kathmandu">(GMT) Kathmandu</option>
	<option value="Asia/Katmandu">(GMT) Katmandu</option>
	<option value="Indian/Kerguelen">(GMT) Kerguelen</option>
	<option value="Africa/Khartoum">(GMT) Khartoum</option>
	<option value="Africa/Kigali">(GMT) Kigali</option>
	<option value="Pacific/Kiritimati">(GMT) Kiritimati</option>
	<option value="Asia/Kolkata">(GMT) Kolkata</option>
	<option value="Pacific/Kosrae">(GMT) Kosrae</option>
	<option value="Asia/Kuala_Lumpur">(GMT) Kuala Lumpur</option>
	<option value="Asia/Kuching">(GMT) Kuching</option>
	<option value="Asia/Kuwait">(GMT) Kuwait</option>
	<option value="Pacific/Kwajalein">(GMT) Kwajalein</option>
	<option value="America/La_Paz">(GMT) La Paz</option>
	<option value="Africa/Lagos">(GMT) Lagos</option>
	<option value="Africa/Libreville">(GMT) Libreville</option>
	<option value="America/Lima">(GMT) Lima</option>
	<option value="Australia/Lindeman">(GMT) Lindeman</option>
	<option value="Europe/Lisbon">(GMT) Lisbon</option>
	<option value="Europe/London">(GMT) London</option>
	<option value="Africa/Luanda">(GMT) Luanda</option>
	<option value="Africa/Lusaka">(GMT) Lusaka</option>
	<option value="Asia/Macao">(GMT) Macao</option>
	<option value="Asia/Macau">(GMT) Macau</option>
	<option value="America/Maceio">(GMT) Maceio</option>
	<option value="Atlantic/Madeira">(GMT) Madeira</option>
	<option value="Indian/Mahe">(GMT) Mahe</option>
	<option value="Pacific/Majuro">(GMT) Majuro</option>
	<option value="Asia/Makassar">(GMT) Makassar</option>
	<option value="Africa/Malabo">(GMT) Malabo</option>
	<option value="Indian/Maldives">(GMT) Maldives</option>
	<option value="America/Managua">(GMT) Managua</option>
	<option value="America/Manaus">(GMT) Manaus</option>
	<option value="Asia/Manila">(GMT) Manila</option>
	<option value="Africa/Maputo">(GMT) Maputo</option>
	<option value="America/Marigot">(GMT) Marigot</option>
	<option value="Pacific/Marquesas">(GMT) Marquesas</option>
	<option value="America/Martinique">(GMT) Martinique</option>
	<option value="Africa/Maseru">(GMT) Maseru</option>
	<option value="Indian/Mauritius">(GMT) Mauritius</option>
	<option value="Antarctica/Mawson">(GMT) Mawson</option>
	<option value="Indian/Mayotte">(GMT) Mayotte</option>
	<option value="Africa/Mbabane">(GMT) Mbabane</option>
	<option value="America/Mendoza">(GMT) Mendoza</option>
	<option value="Pacific/Midway">(GMT) Midway</option>
	<option value="Africa/Mogadishu">(GMT) Mogadishu</option>
	<option value="Africa/Monrovia">(GMT) Monrovia</option>
	<option value="America/Montserrat">(GMT) Montserrat</option>
	<option value="Asia/Muscat">(GMT) Muscat</option>
	<option value="Africa/Nairobi">(GMT) Nairobi</option>
	<option value="Pacific/Nauru">(GMT) Nauru</option>
	<option value="Africa/Ndjamena">(GMT) Ndjamena</option>
	<option value="Africa/Niamey">(GMT) Niamey</option>
	<option value="Pacific/Niue">(GMT) Niue</option>
	<option value="Pacific/Norfolk">(GMT) Norfolk</option>
	<option value="America/Noronha">(GMT) Noronha</option>
	<option value="Australia/North">(GMT) North</option>
	<option value="Africa/Nouakchott">(GMT) Nouakchott</option>
	<option value="Pacific/Noumea">(GMT) Noumea</option>
	<option value="Asia/Oral">(GMT) Oral</option>
	<option value="Africa/Ouagadougou">(GMT) Ouagadougou</option>
	<option value="Pacific/Pago_Pago">(GMT) Pago Pago</option>
	<option value="America/Panama">(GMT) Panama</option>
	<option value="America/Paramaribo">(GMT) Paramaribo</option>
	<option value="Australia/Perth">(GMT) Perth</option>
	<option value="Asia/Phnom_Penh">(GMT) Phnom Penh</option>
	<option value="America/Phoenix">(GMT) Phoenix</option>
	<option value="Pacific/Pitcairn">(GMT) Pitcairn</option>
	<option value="Asia/Pontianak">(GMT) Pontianak</option>
	<option value="America/Port-au-Prince">(GMT) Port-au-Prince</option>
	<option value="America/Port_of_Spain">(GMT) Port of Spain</option>
	<option value="Africa/Porto-Novo">(GMT) Porto-Novo</option>
	<option value="America/Porto_Acre">(GMT) Porto Acre</option>
	<option value="America/Porto_Velho">(GMT) Porto Velho</option>
	<option value="America/Puerto_Rico">(GMT) Puerto Rico</option>
	<option value="Asia/Pyongyang">(GMT) Pyongyang</option>
	<option value="Asia/Qatar">(GMT) Qatar</option>
	<option value="Australia/Queensland">(GMT) Queensland</option>
	<option value="Asia/Qyzylorda">(GMT) Qyzylorda</option>
	<option value="Asia/Rangoon">(GMT) Rangoon</option>
	<option value="Pacific/Rarotonga">(GMT) Rarotonga</option>
	<option value="America/Recife">(GMT) Recife</option>
	<option value="America/Regina">(GMT) Regina</option>
	<option value="Indian/Reunion">(GMT) Reunion</option>
	<option value="Atlantic/Reykjavik">(GMT) Reykjavik</option>
	<option value="America/Rio_Branco">(GMT) Rio Branco</option>
	<option value="Asia/Riyadh">(GMT) Riyadh</option>
	<option value="America/Rosario">(GMT) Rosario</option>
	<option value="Antarctica/Rothera">(GMT) Rothera</option>
	<option value="Asia/Saigon">(GMT) Saigon</option>
	<option value="Pacific/Saipan">(GMT) Saipan</option>
	<option value="Asia/Samarkand">(GMT) Samarkand</option>
	<option value="Pacific/Samoa">(GMT) Samoa</option>
	<option value="US/Samoa">(GMT) Samoa</option>
	<option value="America/Santarem">(GMT) Santarem</option>
	<option value="America/Santo_Domingo">(GMT) Santo Domingo</option>
	<option value="Africa/Sao_Tome">(GMT) Sao Tome</option>
	<option value="Canada/Saskatchewan">(GMT) Saskatchewan</option>
	<option value="Asia/Seoul">(GMT) Seoul</option>
	<option value="Asia/Shanghai">(GMT) Shanghai</option>
	<option value="Asia/Singapore">(GMT) Singapore</option>
	<option value="America/St_Barthelemy">(GMT) St Barthelemy</option>
	<option value="Atlantic/St_Helena">(GMT) St Helena</option>
	<option value="America/St_Kitts">(GMT) St Kitts</option>
	<option value="America/St_Lucia">(GMT) St Lucia</option>
	<option value="America/St_Thomas">(GMT) St Thomas</option>
	<option value="America/St_Vincent">(GMT) St Vincent</option>
	<option value="America/Swift_Current">(GMT) Swift Current</option>
	<option value="Antarctica/Syowa">(GMT) Syowa</option>
	<option value="Pacific/Tahiti">(GMT) Tahiti</option>
	<option value="Asia/Taipei">(GMT) Taipei</option>
	<option value="Asia/Tashkent">(GMT) Tashkent</option>
	<option value="Asia/Tbilisi">(GMT) Tbilisi</option>
	<option value="America/Tegucigalpa">(GMT) Tegucigalpa</option>
	<option value="Asia/Thimbu">(GMT) Thimbu</option>
	<option value="Asia/Thimphu">(GMT) Thimphu</option>
	<option value="Africa/Timbuktu">(GMT) Timbuktu</option>
	<option value="Asia/Tokyo">(GMT) Tokyo</option>
	<option value="Pacific/Tongatapu">(GMT) Tongatapu</option>
	<option value="America/Tortola">(GMT) Tortola</option>
	<option value="Africa/Tripoli">(GMT) Tripoli</option>
	<option value="Asia/Ujung_Pandang">(GMT) Ujung Pandang</option>
	<option value="Asia/Ulaanbaatar">(GMT) Ulaanbaatar</option>
	<option value="Asia/Ulan_Bator">(GMT) Ulan Bator</option>
	<option value="Asia/Urumqi">(GMT) Urumqi</option>
	<option value="Asia/Vientiane">(GMT) Vientiane</option>
	<option value="America/Virgin">(GMT) Virgin</option>
	<option value="Antarctica/Vostok">(GMT) Vostok</option>
	<option value="Australia/West">(GMT) West</option>
	<option value="Brazil/West">(GMT) West</option>
	<option value="Europe/Amsterdam">(GMT +01:00) Amsterdam</option>
	<option value="Europe/Andorra">(GMT +01:00) Andorra</option>
	<option value="Europe/Belgrade">(GMT +01:00) Belgrade</option>
	<option value="Europe/Berlin">(GMT +01:00) Berlin</option>
	<option value="Europe/Bratislava">(GMT +01:00) Bratislava</option>
	<option value="Europe/Brussels">(GMT +01:00) Brussels</option>
	<option value="Europe/Budapest">(GMT +01:00) Budapest</option>
	<option value="Africa/Ceuta">(GMT +01:00) Ceuta</option>
	<option value="Europe/Copenhagen">(GMT +01:00) Copenhagen</option>
	<option value="Europe/Gibraltar">(GMT +01:00) Gibraltar</option>
	<option value="Atlantic/Jan_Mayen">(GMT +01:00) Jan Mayen</option>
	<option value="Europe/Ljubljana">(GMT +01:00) Ljubljana</option>
	<option value="Arctic/Longyearbyen">(GMT +01:00) Longyearbyen</option>
	<option value="Europe/Luxembourg">(GMT +01:00) Luxembourg</option>
	<option value="Europe/Madrid">(GMT +01:00) Madrid</option>
	<option value="Europe/Malta">(GMT +01:00) Malta</option>
	<option value="Europe/Monaco">(GMT +01:00) Monaco</option>
	<option value="Europe/Oslo">(GMT +01:00) Oslo</option>
	<option value="Europe/Paris">(GMT +01:00) Paris</option>
	<option value="Europe/Podgorica">(GMT +01:00) Podgorica</option>
	<option value="Europe/Prague">(GMT +01:00) Prague</option>
	<option value="Europe/Rome">(GMT +01:00) Rome</option>
	<option value="Europe/San_Marino">(GMT +01:00) San Marino</option>
	<option value="Europe/Sarajevo">(GMT +01:00) Sarajevo</option>
	<option value="Europe/Skopje">(GMT +01:00) Skopje</option>
	<option value="Europe/Stockholm">(GMT +01:00) Stockholm</option>
	<option value="Europe/Tirane">(GMT +01:00) Tirane</option>
	<option value="Africa/Tunis">(GMT +01:00) Tunis</option>
	<option value="Europe/Vaduz">(GMT +01:00) Vaduz</option>
	<option value="Europe/Vatican">(GMT +01:00) Vatican</option>
	<option value="Europe/Vienna">(GMT +01:00) Vienna</option>
	<option value="Europe/Warsaw">(GMT +01:00) Warsaw</option>
	<option value="Africa/Windhoek">(GMT +01:00) Windhoek</option>
	<option value="Europe/Zagreb">(GMT +01:00) Zagreb</option>
	<option value="Europe/Zurich">(GMT +01:00) Zurich</option>
	<option value="Asia/Amman">(GMT +02:00) Amman</option>
	<option value="Europe/Athens">(GMT +02:00) Athens</option>
	<option value="Asia/Beirut">(GMT +02:00) Beirut</option>
	<option value="Europe/Bucharest">(GMT +02:00) Bucharest</option>
	<option value="Africa/Cairo">(GMT +02:00) Cairo</option>
	<option value="Europe/Chisinau">(GMT +02:00) Chisinau</option>
	<option value="Asia/Damascus">(GMT +02:00) Damascus</option>
	<option value="Asia/Gaza">(GMT +02:00) Gaza</option>
	<option value="Europe/Helsinki">(GMT +02:00) Helsinki</option>
	<option value="Europe/Istanbul">(GMT +02:00) Istanbul</option>
	<option value="Asia/Istanbul">(GMT +02:00) Istanbul</option>
	<option value="Asia/Jerusalem">(GMT +02:00) Jerusalem</option>
	<option value="Europe/Kaliningrad">(GMT +02:00) Kaliningrad</option>
	<option value="Europe/Kiev">(GMT +02:00) Kiev</option>
	<option value="Europe/Mariehamn">(GMT +02:00) Mariehamn</option>
	<option value="Europe/Minsk">(GMT +02:00) Minsk</option>
	<option value="Europe/Nicosia">(GMT +02:00) Nicosia</option>
	<option value="Asia/Nicosia">(GMT +02:00) Nicosia</option>
	<option value="Europe/Riga">(GMT +02:00) Riga</option>
	<option value="Europe/Simferopol">(GMT +02:00) Simferopol</option>
	<option value="Europe/Sofia">(GMT +02:00) Sofia</option>
	<option value="Europe/Tallinn">(GMT +02:00) Tallinn</option>
	<option value="Asia/Tel_Aviv">(GMT +02:00) Tel Aviv</option>
	<option value="Europe/Tiraspol">(GMT +02:00) Tiraspol</option>
	<option value="Europe/Uzhgorod">(GMT +02:00) Uzhgorod</option>
	<option value="Europe/Vilnius">(GMT +02:00) Vilnius</option>
	<option value="Europe/Zaporozhye">(GMT +02:00) Zaporozhye</option>
	<option value="Europe/Moscow">(GMT +03:00) Moscow</option>
	<option value="Europe/Volgograd">(GMT +03:00) Volgograd</option>
	<option value="Asia/Tehran">(GMT +03:30) Tehran</option>
	<option value="Asia/Baku">(GMT +04:00) Baku</option>
	<option value="Europe/Samara">(GMT +04:00) Samara</option>
	<option value="Asia/Yerevan">(GMT +04:00) Yerevan</option>
	<option value="Asia/Karachi">(GMT +05:00) Karachi</option>
	<option value="Asia/Yekaterinburg">(GMT +05:00) Yekaterinburg</option>
	<option value="Asia/Novokuznetsk">(GMT +06:00) Novokuznetsk</option>
	<option value="Asia/Novosibirsk">(GMT +06:00) Novosibirsk</option>
	<option value="Asia/Omsk">(GMT +06:00) Omsk</option>
	<option value="Asia/Krasnoyarsk">(GMT +07:00) Krasnoyarsk</option>
	<option value="Asia/Irkutsk">(GMT +08:00) Irkutsk</option>
	<option value="Asia/Yakutsk">(GMT +09:00) Yakutsk</option>
	<option value="Australia/Adelaide">(GMT +09:30) Adelaide</option>
	<option value="Australia/Broken_Hill">(GMT +09:30) Broken Hill</option>
	<option value="Australia/South">(GMT +09:30) South</option>
	<option value="Australia/Yancowinna">(GMT +09:30) Yancowinna</option>
	<option value="Australia/ACT">(GMT +10:00) ACT</option>
	<option value="Australia/Canberra">(GMT +10:00) Canberra</option>
	<option value="Australia/Currie">(GMT +10:00) Currie</option>
	<option value="Australia/Hobart">(GMT +10:00) Hobart</option>
	<option value="Australia/Melbourne">(GMT +10:00) Melbourne</option>
	<option value="Australia/NSW">(GMT +10:00) NSW</option>
	<option value="Asia/Sakhalin">(GMT +10:00) Sakhalin</option>
	<option value="Australia/Sydney">(GMT +10:00) Sydney</option>
	<option value="Australia/Tasmania">(GMT +10:00) Tasmania</option>
	<option value="Australia/Victoria">(GMT +10:00) Victoria</option>
	<option value="Asia/Vladivostok">(GMT +10:00) Vladivostok</option>
	<option value="Australia/LHI">(GMT +10:30) LHI</option>
	<option value="Australia/Lord_Howe">(GMT +10:30) Lord Howe</option>
	<option value="Asia/Magadan">(GMT +11:00) Magadan</option>
	<option value="Asia/Anadyr">(GMT +12:00) Anadyr</option>
	<option value="Pacific/Auckland">(GMT +12:00) Auckland</option>
	<option value="Asia/Kamchatka">(GMT +12:00) Kamchatka</option>
	<option value="Antarctica/McMurdo">(GMT +12:00) McMurdo</option>
	<option value="Antarctica/South_Pole">(GMT +12:00) South Pole</option>
	<option value="Pacific/Chatham">(GMT +12:45) Chatham</option>
</select>